### ISSUE TITLE
Lack of diversity in synthesized images

### ISSUE THREAD

**Issue by paathelb** [pfriedri/cwdm#2]
Thanks for the nice work and the great documentation! So I followed exactly your instructions and tried synthesizing 20 samples for a subset of the BRATS2023 validation data for the missing sequence using the pretrained model given. But I wonder why using different seeds for the 20 samples, the synthesized images are almost exactly the same with very little (almost neglible) variations?

Example samples for the same slice using seeds 44, 45, and 46

![0](https://github.com/user-attachments/assets/267480e3-6a13-492a-934e-00474eb92ffc)

![1](https://github.com/user-attachments/assets/db246cb7-878d-4dcf-bed1-216388f7fd8c)

![2](https://github.com/user-attachments/assets/533b57f5-9708-4113-8ad6-fb5a8ea05182)

Almost similar results with the other 17 seeds.
And this is true for all the other slices.

**Comment by pfriedri** [comment]
@paathelb that's what I would expect. While diffusion models are known for their diverse image generation capabilities, we apply a strong condition to the generation process. The generation process remains non-deterministic, so even without changing any random seed you would generate slightly different images. The results however should - due to the condition applied in the generation process - be very similar. The task of the model is not to generate a diverse set of plausible missing modality images, but generate the one image, that actually matches the ground truth.
